/////////////////////////////
// WEAPON PRESELECT OBJECT //
/////////////////////////////

const preSelects = {
	ordnance: {
		battlecannon: {
			fine: {		//cost: 1573, weight: 485,
				name: "Fine Battlecannon",
				type: "p",
				strength: 8,
				die1: 8,
				die2: 8,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 72,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 2,
				weightmod: 1
			},
			ordinary: {	//cost: 863, weight:390
				name: "Battlecannon",
				type: "p",
				strength: 8,
				die1: 8,
				die2: 8,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 72,
				accx: 2,
				accY: 1,
				rof: 0,
				blast: 2,
				weightMod: 1
			},
			poor: {		//cost:170, weight: 665,
				name: "Poor Battlecannon",
				type: "p",
				strength: 8,
				die1: 8,
				die2: 6,
				delay: 1,
				ordRat: 4,
				cat: 0.33,
				range: 72,
				accx: 3,
				accy: 1,
				rof: 0,
				blast: 2,
				weightMod: 2
			}
		},
		punshisher: {
			fine: {		//cost: 1672, weight: 625
				name: "Fine Punisher Cannon",
				type: "p",
				strength: 6,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 48,
				accx: 1,
				accy: 2,
				rof: 3,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost: 845, weight:375
				name: "Punisher Cannon",
				type: "p",
				strength: 6,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 36,
				accx: 1,
				accy: 1,
				rof: 3,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost: 228, weight: 515
				name: "Poor Punisher Cannon",
				type: "p",
				strength: 6,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 3,
				blast: 0,
				weightMod: 2
			}
		}, 
		novaBlaster: {
			fine: {		//cost: 1661, weight: 540
				name: "Fine Nova Blaster",
				type: "e",
				strength: 6,
				die1: 12,
				die2: 10,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 48,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 2,
				weightMod: 1	
			},
			ordinary: {	//cost:837, weight:415
				name: "Nova Blaster",
				type: "e",
				strength: 6,
				die1: 10,
				die2: 10,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 48,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 2,
				weightMod: 1
			},
			poor: {		//cost:257, weight:810
				name: "Poor Nova Blaster",
				type: "e",
				strength: 6,
				die1: 10,
				die2: 10,
				delay: 1,
				ordRat: 3,
				cat: 0.33,
				range: 48,
				accx: 3,
				accy: 1,
				rof: 0,
				blast: 2,
				weightMod: 2
			}
		},
		plasmaExecutioner: {
			
			fine: {		//cost:1493, weight: 465
				name: "Fine Plasma Executioner",
				type: "e",
				strength: 7,
				die1: 8,
				die2: 8,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 48,
				accx: 1,
				accy: 2,
				rof: 1,
				blast: 1,
				weightMod: 1
			},
			ordinary: {		//cost: 755, weight: 355
				name: "Plasma Executioner",
				type: "e",
				strength: 7,
				die1: 8,
				die2: 8,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 36,
				accx: 1,
				accy: 1,
				rof: 1,
				blast: 1,
				weightMod: 1
			},
			poor: {		//cost:194, weight: 525
				name: "Poor Plasma Executioner",
				type: "e",
				strength: 7,
				die1: 8,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.33,
				range: 36,
				accx: 2,
				accy: 1,
				rof: 1,
				blast: 1,
				weightMod: 2
			}
		}
		
	},
	heavy: {
		lascannon: {
			fine: {	//cost:909, weight:185
				name: "Fine Lascannon",
				type: "e",
				strength: 9,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 48,
				accx: 1,
				accy: 2,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:557, weight: 150
				name: "Lascannon",
				type: "e",
				strength: 9,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 48,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:171, weight: 260
				name: "Poor Lascannon",
				type: "e",
				strength: 9,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 48,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 2
			}
		},
		plasmaCannon: {
			fine: {		//cost:1082, weight:210
				name: "Fine Plasma Cannon",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 48,
				accx: 1,
				accy: 2,
				rof: 0,
				blast: 2,
				weightMod: 1
			},
			ordinary: {	//cost:547, weight:140
				name: "Plasma Cannon",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 36,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 2,
				weightMod: 1
			},
			poor: {	//cost:119, weight:235
				name: "Poor Plasma Cannon",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 0.666,
				ordRat: 2,
				cat: 0.5,
				range: 36,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 2,
				weightMod: 2
			}
		},
		heavyBolter: {
			fine: {	//cost:1217, weight:230
				name: "Fine Heavy Bolter",
				type: "p",
				strength: 5,
				die1: 8,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 48,
				accx: 1,
				accy: 2,
				rof: 2,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:616, weight:150
				name: "Heavy Bolter",
				type: "p",
				strength: 5,
				die1: 8,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 36,
				accx: 1,
				accy: 1,
				rof: 2,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:150, weight:210
				name: "Poor Heavy Bolter",
				type: "p",
				strength: 5,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 36,
				accx: 2,
				accy: 1,
				rof: 2,
				blast: 0,
				weightMod: 2
			}
		},
		heavyStubber: {
			fine: {	//cost:277, weight:155
				name: "Fine Heavy Stubber",
				type: "p",
				strength: 4,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 36,
				accx: 1,
				accy: 1,
				rof: 3,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:149, weight:95
				name: "Heavy Stubber",
				type: "p",
				strength: 4,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 3,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:37, weight:110
				name: "Poor Heavy Stubber",
				type: "p",
				strength: 4,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 0.5,
				range: 24,
				accx: 3,
				accy: 1,
				rof: 2,
				blast: 0,
				weightMod: 2
			}
		},
	},
	basic: {
		lasgun: {
			fine: {	//cost:154, weight:60
				name: "Fine Lasgun",
				type: "e",
				strength: 3,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 36,
				accx: 1,
				accy: 2,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:55, weight:30
				name: "Lasgun",
				type: "e",
				strength: 3,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:19, weight:45
				name: "Poor Lasgun",
				type: "e",
				strength: 3,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 2
			}
		},
		boltgun: {
			fine: {	//cost:326, weight:60
				name: "Fine Boltgun",
				type: "p",
				strength: 4,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 30,
				accx: 1,
				accy: 2,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:112, weight:35
				name: "Boltgun",
				type: "p",
				strength: 4,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:52, weight:25
				name: "Poor Boltgun",
				type: "p",
				strength: 4,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			}
		},
		autogun: {
			fine: {	//cost:69, weight:35
				name: "Fine Autogun",
				type: "p",
				strength: 3,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 1,
				accy: 1,
				rof: 1,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:22, weight:20
				name: "Autogun",
				type: "p",
				strength: 3,
				die1: 4,
				die2: 2,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:8, weight:15
				name: "Poor Autogun",
				type: "p",
				strength: 3,
				die1: 2,
				die2: 2,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 3,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			}
		},
		plasmagun: {
			fine: {	//cost:357, weight:60
				name: "Fine Plasma Gun",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 1,
				accy: 1,
				rof: 1,
				blast: 0,
				weightMod: 1
			},
			ordinary: {	//cost:168, weight:55
				name: "Plasma Gun",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 0.666,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 2,
				accy: 1,
				rof: 1,
				blast: 0,
				weightMod: 1
			},
			poor: {	//cost:95, weight:50
				name: "Poor Plasma Gun",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 0.666,
				ordRat: 2,
				cat: 1,
				range: 24,
				accx: 4,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			}
		}
	},
	pistol: {
		laspistol: {
			fine: { //cost:71, weight:25
				name: "Fine Laspistol",
				type: "e",
				strength: 3,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 18,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
				
			},
			ordinary: { //cost:39, weight:20
				name: "Laspistol",
				type: "e",
				strength: 3,
				die1: 4,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 1,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: { //cost:17, weight:15
				name: "Poor Laspistol",
				type: "e",
				strength: 3,
				die1: 2,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			}
		},
		boltpistol: {
			fine: { //cost:143, weight:30
				name: "Fine Boltpistol",
				type: "p",
				strength: 4,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 1,
				accy: 2,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			ordinary: { //cost:88, weight:25
				name: "Boltpistol",
				type: "p",
				strength: 4,
				die1: 6,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: { //cost:53, weight:20
				name: "Poor Boltpistol",
				type: "p",
				strength: 4,
				die1: 4,
				die2: 6,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 3,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			}
		},
		plasmapistol: {
			fine: { //cost:468, weight:25
				name: "Fine Plasma pistol",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 0.666,
				ordRat: 2,
				cat: 2,
				range: 18,
				accx: 2,
				accy: 1,
				rof: 1,
				blast: 0,
				weightMod: 0.5
			},
			ordinary: { //cost:211, weight:20
				name: "Plasma pistol",
				type: "e",
				strength: 7,
				die1: 6,
				die2: 6,
				delay: 0.5,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 2,
				accy: 1,
				rof: 1,
				blast: 0,
				weightMod: 0.5
			},
			poor: {
				name: "Poor Plasma pistol",
				type: "e",
				strength: 7,
				die1: 4,
				die2: 6,
				delay: 0.5,
				ordRat: 2,
				cat: 2,
				range: 6,
				accx: 2,
				accy: 1,
				rof: 1,
				blast: 0,
				weightMod: 1
			}
		},
		stubgun: {
			fine: { //cost:33, weight:20
				name: "Fine Stub gun",
				type: "p",
				strength: 3,
				die1: 2,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 1,
				accy: 3,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			ordinary: { //cost:17, weight:15
				name: "Stub gun",
				type: "p",
				strength: 3,
				die1: 2,
				die2: 4,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			},
			poor: { //cost:5, weight:10
				name: "Poor Stub gun",
				type: "p",
				strength: 2,
				die1: 2,
				die2: 2,
				delay: 1,
				ordRat: 2,
				cat: 2,
				range: 12,
				accx: 2,
				accy: 1,
				rof: 0,
				blast: 0,
				weightMod: 1
			}
		}
	}
};